### ISSUE TITLE
config: change node to testnet.gamedao.co

### ISSUE THREAD

**Issue by soundyogi** [gamedaoco/gamedao-beta#146]

**Comment by 5-mark** [comment]
@soundyogi are you able to review this ticket? please review if so.
Thanks,
Inan

**Comment by 2075** [comment]
as communicated yesterday: due to instability of node and varying feedback of testers i have changed this back to the alphaville full node until resolved.

**Comment by 5-mark** [comment]
@2075 then can we close this ticket?

**Comment by 2075** [comment]
no,
_"as communicated yesterday: due to instability of node and varying feedback of testers i have changed this back to the alphaville full node **until resolved**."_

therefore i suggest we:
1 check first why the new node is slow
2 change config to new node again
3 confirm it works
4 close the ticket
