### ISSUE TITLE
create dao: values get overwritten on wallet change and cancel tx, should not

### ISSUE THREAD

**Issue by soundyogi** [gamedaoco/gamedao-beta#217]
a refresh is triggered that initializes the values in the forms- this needs branching probably

**Comment by 5-mark** [comment]
I fear this ticket was misunderstood due to lack of specification. 
The implementation now keeps all inputs in all fields even after reload of the page and after switching wallet address or logout and re-login.
I would have understood this ticket as such that entered form values just dont get overwritten when switching wallet address or canceling trx - but that doesnt mean we have to keep all entered values forever. 

Lets discuss this ticket, so I can write proper ACs. (@soundyogi, @2075)

**Comment by soundyogi** [comment]
well it is a usecase ( I created a ton of campaigns and when you write long markdown it SUCKS when its all gone so I used external txt files now I dont have to.)

so the form should always be initialized on reload or what is the desired behavior?

**Comment by 2075** [comment]
- data can be cached until the campaign was created
- if you desire to copy/edit the data, this should be done by loading data from ipfs and writing it back (needs to maintain the cid or needs to be updated in a transaction for the e.g. campaign. )
- same process also for org and voting

**Comment by soundyogi** [comment]
k, I will delete the localStorage data when the TX clears
the next step is the edit pages then, which is another ticket itself
