### ISSUE TITLE
Frontend: Fix Forms Wallet connection.

### ISSUE THREAD

**Issue by soundyogi** [gamedaoco/gamedao-beta#49]
wallet / account selector code has changed and broke the forms.

accountPair is null.

see organisations/Create.jsx 
(but also campaigns)

**Comment by soundyogi** [comment]
Reproduce: "Create DAO" in /organisations

![image](https://user-images.githubusercontent.com/3201046/140417331-a8422e12-43da-431d-b55a-9d3031c9c639.png)

**Comment by 2075** [comment]
please close when done @5-mark

**Comment by 5-mark** [comment]
@soundyogi  & @2075: I cannot reproduce as described (Reproduce: "Create DAO" in /organisations), as the organisations page is broken and creating a new campaign results in an empty page. 

please use bug tickets for this kind of issues and fill out steps to reproduce - otherwise I have a hard time to find out what this is about.

**Comment by soundyogi** [comment]
yeah this seems to keep breaking with the work being done on wallet / focus on restoring functionality I will do tonight
